---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influx-data
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path