---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age15906aq8dva7sujtvxd2z5j55xud365zdt5wnkfhtcczyfkq0y4vsufdem8
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age15906aq8dva7sujtvxd2z5j55xud365zdt5wnkfhtcczyfkq0y4vsufdem8
