---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1g2wnxdjrrq4nkzejddppfgwg4mccxmczc0086lrlq7n5al2hhvasw8uh3f
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1g2wnxdjrrq4nkzejddppfgwg4mccxmczc0086lrlq7n5al2hhvasw8uh3f
