---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: code-server
  namespace: apps
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.pascaliske.dev
      chart: code-server
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: code-server-charts
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    image:
      repository: codercom/code-server
      tag: 4.0.2
    ports:
      http:
        enabled: true
        port: 8080
    configMap:
      create: true
      mountPath: /etc/code-server
    securityContext:
      fsGroup: 1000
      runAsNonRoot: true
      runAsGroup: 1000
      runAsUser: 1000
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: code-server.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - code-server.${SECRET_DOMAIN}
            secretName: "code-server-tls"
    persistence:
      config:
        enabled: true
        existingClaim: code-data