---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: code-server-charts
  namespace: flux-system
spec:
  interval: 15m
  url: https://charts.pascaliske.dev
  timeout: 3m