---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: code-server-charts
  namespace: flux-system
spec:
  interval: 15m
  url: https://github.com/coder/code-server
  timeout: 3m