esphome:
  name: example-sensor
  platform: ESP32
  board: esp32dev

# Enable logging
logger:

# Enable Home Assistant API
api:

# Over-the-air update password
ota:
  password: "b6b98a48cfa9e2d68286366cd3e24694"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "example-sensor Fallback Hotspot"
    password: "cUOywJMWaaaB"

captive_portal:

# DHT11 Temperature, Humidity, and Internal Hall sensor configuration
sensor:
  - platform: dht
    pin: 15
    temperature:
      name: "example-sensor-temp"
    humidity:
      name: "example-sensor-humidity"
    update_interval: 60s
  - platform: esp32_hall
    name: "underbed-sensor-hall-effect"
    update_interval: 60s