apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:rWgzsjnCo4ra9eyJpMFPGD8jW2qa,iv:1lRG8MKiag6MUUvUocLJmFLIcYo2vwBuEIW0CH/sTbQ=,tag:IBtAmduGX9kQYZktWbttxA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:CPn+3zhdTToJnTi6+ZXntXzy5x0=,iv:ECTS2xwlptC0Zo1/WFUqqqRnsDODFuGx1M+sMSbVJ4s=,tag:jPgZ1s80v8pg8I6fO9lMzQ==,type:str]
    SECRET_CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:FQMGIfThD31Scw4gHHYqgxeW8OP8isnl1eGzr+pFOHyOFVtIjg==,iv:aijlt+P5a8w5YhwsMFbRjicMokoUYO7cL9B3+SIga7Q=,tag:kJdMQ4I+AfsyS9lcr+NSGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15906aq8dva7sujtvxd2z5j55xud365zdt5wnkfhtcczyfkq0y4vsufdem8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrR2oyWlU1NXRYQ2Znb1M5
            TmNUZkhuOEppUXc5N21EbVJNQlUrUmkydUhjCm9jQm9KK3JwSHJKRE1JUVJNR3JZ
            dWc0ekVwVzdoK0lON3lzallxak1QZ2MKLS0tIEFyYzFDeGMwQTZUUDRPM3QwcnNs
            Y0JpUHVuMDhjVWJYTzEyblFiZkVybDAKTCnDtnsBiPx7Yk9WAff0TshcHyA5JPlB
            pTVfEYjRDIgcN4q7XnstpvMenILB1y6fb1A/ZRHFfzIM6UnssN4Ygw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-19T17:23:25Z"
    mac: ENC[AES256_GCM,data:prHWU+UoLOYC8GZnp+yQONa0D21ShCVYfiZxYBPtI10yzrAXoPMr/wY+hPKK/sVhuv2dHpPbU32OlWhIEtlZ8U9dlXlUg2ISnsQVIUplkPL73jJ4bnlmD7Zhw+spJrzgGaT2OW9HOmgH0+CGFcA9uAnOJoGKXv203Eg9lsKvNoQ=,iv:6HZ901izCMbiFeI4zyqk6QVNZpltRPlIch9dkBMTvOQ=,tag:BWgExCVqfARShXcQPrN6AA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
