---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflare-exporter
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://lablabs.github.io/cloudflare-exporter
      chart: cloudflare-exporter/cloudflare-exporter
      version: 0.1.8
      sourceRef:
        kind: HelmRepository
        name: lablabs-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/lablabs/cloudflare_exporter
      tag: 0.0.9
    replicas: 1
    service:
      type: ClusterIP
      port: 8080
      annotations:
        prometheus.io/probe: "true"
      addPrometheusScrapeAnnotation: true
    env:
      - name: CF_API_EMAIL
        value: "${SECRET_CLOUDFLARE_EMAIL}"
      - name: CF_API_KEY
        value: "${SECRET_CLOUDFLARE_APIKEY}"
      - name: FREE_TIER
        value: "true"
      - name: CF_ZONES
        value: "4c8964bcb8e7e3845315e5c0bf4eee50"