---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://jaegertracing.github.io/helm-charts
      chart: jaeger
      version: 0.55.0
      sourceRef:
        kind: HelmRepository
        name: jaeger-charts
        namespace: flux-system
      interval: 5m
  values:
    replicas: 1
    allInOne:
      enabled: true
      image: jaegertracing/all-in-one
      tag: 1.31.0
      pullPolicy: IfNotPresent
    provisionDataStore:
      cassandra: false
    storage:
      type: none
    agent:
      enabled: false
    collector:
      enabled: false
    query:
      enabled: false
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
      hosts:
        - "jaeger.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - "jaeger.${SECRET_DOMAIN}"
          secretName: "jaeger-tls"
    #serviceAccount: 
      #create: true
    resources:
      requests:
        memory: 100Mi
        cpu: 500m
      limits:
        memory: 500Mi