---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-data
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
