apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:2pYZY/pmzTF6rIa/D4bjn9WCPUBFVui5CBYtMT3kEkR5NlRCY12EYg==,iv:cvV3UgzLrunv53HQopb66fxgPFzIV5xPumORCA89r1Y=,tag:arsWhonNrEDO/jpwa/4llw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15906aq8dva7sujtvxd2z5j55xud365zdt5wnkfhtcczyfkq0y4vsufdem8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByb3UwRTJQY1gyUWNURFRD
            QSs4bXk4QlpNL2M5cHBSZXFxcnVWeVJZOXhjCjVCWXcrTlQzMGF1enJPRzVwV1pw
            dVNTaDY5YVdCVkNJVHpJOTlBU1l2NG8KLS0tIFNNVHliMW50Wm5oRGwyVW9iZ3o1
            VTlUQnJaVG5EQUVnRmFQQUp6Sm1tbncKR1sgj5E+B63Na9ZgIR6xxBVJuY0OO3sv
            QRpQTe6Qk3Lgjhe0FgCMxeCBgKkuuE1z+ZUrgB9Fs5J9ySwrx7+HLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-23T19:42:48Z"
    mac: ENC[AES256_GCM,data:WG/0CUuIH078RK3xWrgbsiCJyVtsIbz6wYsRcqj83zbIwqqDO6zG2jAqIkm/vaAfKOhGccf6di47fJ2djU7n2NyGDFKNRQ2q7EzkHoROBtEwrH3Q47giGrAwrFh6lTr9sF8YkAv9oQQDtTu8IeQWyp19Wc+fVjO8ScLCO7rfAAw=,iv:FpXrhCiTFPVhPeWfCHRXFkLGtOAyVvjdI2QPMeZtzQA=,tag:2n1d9P87oW+5DVmwkP9hJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
