name: Broken Link Check

on:
  workflow_dispatch:
  push:

jobs:
  linkChecker:
    #if: ${{ github.event.deployment_status.description == 'Deploy Preview' && github.event.deployment_status.state == 'success'  }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            consul/**
            **.mdx

      - name: Run lychee link checker
        if: steps.changed-files.any_changed == 'true'
        id: lychee
        uses: lycheeverse/lychee-action@v1.6.1
        with:
          args: ${{ steps.changed-files.outputs.all_changed_and_modified_files }} --base https://tutorials-git-${{ github.event.pull_request.number}}-hashicorp.vercel.app/ --exclude-all-private --exclude '\.(svg|gif|jpg|png)' --exclude 'manage\.auth0\.com' --max-concurrency=24 --no-progress --verbose
          # Fail GitHub action when broken links are found?
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Comment on PR with lychee output
        if: env.lychee_exit_code != 0
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: Link Checker Report
          content-filepath: ./lychee/out.md