---
name: Schedule - Renovate Helm Releases

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Dry-Run"
        default: "false"
        required: false
      logLevel:
        description: "Log-Level"
        default: "debug"
        required: false
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main
    paths:
      - ".github/renovate.json5"
      - ".github/renovate/**.json"    

jobs:
  renovate-helm-releases:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1

      - name: Renovate Helm Releases
        uses: k8s-at-home/renovate-helm-releases@v1
        with:
          cluster-path: "./cluster"

      - name: Create pull request for renovatebot helm-release annotations
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: renovate-annotations
          delete-branch: true
          title: "chore(deps): update renovate annotations"
          signoff: false
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit-message: "chore(deps): update renovate annotations"
          body: |
            Update HelmReleases inorder for Renovate to pick up new versions of Helm charts
          labels: renovate/annotations