name: Schedule - Renovate Helm Releases

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Dry-Run"
        default: "false"
        required: false
      logLevel:
        description: "Log-Level"
        default: "debug"
        required: false
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main
    paths:
      - ".github/renovate.json5"
      - ".github/renovate/**.json"

env:
  LOG_LEVEL: debug
  DRY_RUN: false

jobs:
  renovate-helm-releases:
    name: Renovate
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Verify Renovate Configuration
        uses: tj-actions/renovate-config-validator@v1.3
        with:
          config-file: .github/renovate.json5
      - name: Self-hosted Renovate for Helm Release Updates
        uses: renovatebot/github-action@v32.11.3
        with:
          configurationFile: .github/renovate.json5
          token: ${{ secrets.RENOVATE_TOKEN }}